site_name: Moustafa Shaaban

theme:
    name: material
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.expand
        - toc.follow
        - navigation.top
    
    palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
    - Resume: 
        - gis-resume.md
        - web-div-resume.md
    - Projects: 
        - gis-projects.md
        - django-projects.md
    - Tutorials: tutorials/tutorials.md



# Adding the git revision date plugin
plugins:
    - search